name: immich

services:
  immich-server:
    container_name: immich_server
    image: ghcr.io/immich-app/immich-server:${IMMICH_VERSION:-release}
    volumes:
      - ${UPLOAD_LOCATION}:/usr/src/app/upload
      - ${THUMB_LOCATION}:/usr/src/app/upload/thumbs
      - ${ENCODED_VIDEO_LOCATION}:/usr/src/app/upload/encoded-video
      - /etc/localtime:/etc/localtime:ro
      # External library mapping
      - /mnt/raid1/photo_imi:/mnt/media/raid_photos:ro
    env_file:
      - .env
    ports:
      - '2283:2283'
    depends_on:
      - immich_redis
      - immich_postgres
    restart: always
    healthcheck:
      disable: false

  immich-machine-learning:
    container_name: immich_machine_learning
    image: ghcr.io/immich-app/immich-machine-learning:${IMMICH_VERSION:-release}
    volumes:
      - model-cache:/cache
    env_file:
      - .env
    restart: always
    healthcheck:
      disable: false

  # Renamed service to match REDIS_HOSTNAME in .env
  immich_redis:
    container_name: immich_redis
    image: valkey/valkey:8
    healthcheck:
      test: redis-cli ping || exit 1
    restart: always

  # Renamed service to match DB_HOSTNAME in .env
  immich_postgres:
    container_name: immich_postgres
    image: ghcr.io/immich-app/postgres:14-vectorchord0.4.3-pgvectors0.2.0
    environment:
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_DB: ${DB_DATABASE_NAME}
      POSTGRES_INITDB_ARGS: '--data-checksums'
      DB_STORAGE_TYPE: 'HDD'
    volumes:
      - ${DB_DATA_LOCATION}:/var/lib/postgresql/data
    env_file:
      - .env
    restart: always

  # --- ALBUM CREATOR (Disabled temporarily until server is stable) ---
  immich-folder-album-creator:
    image: salvoxia/immich-folder-album-creator:latest
    container_name: immich_folder_album_creator
    restart: unless-stopped
    environment:
      - API_URL=http://immich-server:2283/api
      - API_KEY=jnlBUJotsqwEIhbt9vZND69jn5fCiBByC8KgZbep2Ws
      - ROOT_PATH=/mnt/media/raid_photos/
      - ALBUM_LEVELS=2
      - CRON_EXPRESSION=* * * * *
      - LOG_LEVEL=INFO
    depends_on:
      - immich-server

volumes:
  model-cache:
